// Imports

import fs from "fs-extra"

// Project-Imports

import { Spiky } from "../index";

// Exports

export const writeLine = (code: string): boolean => {
    try {
        fs.writeFileSync("toBeExported.py", code + "\n");
        return true
    } catch (error) {
        console.log(error);
        return false
    }
}
export const startFile = (): boolean => {
    try {
        fs.writeFileSync("toBeExported.py", "# Code generated by spiky.js\n\n\n");
        fs.writeFileSync("toBeExported.py", "# Please buy me a coffee https://buymeacoffee.com/leontm \n\n\n");
        fs.writeFileSync("toBeExported.py", "");
    } catch (error) {
        console.log(error);
        return false;
    }
}